name: Construcción y despliegue de una aplicación MVC a Azure

env:
  AZURE_WEBAPP_NAME: upt-awa-645     # El nombre de tu Azure Web App
  DOTNET_VERSION: '8'                # La versión de .NET que estás usando

on:
  push:
    branches: [ "main" ]             # El flujo se ejecutará cuando haya un push en la rama "main"
    paths:
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:                 # Permite ejecutar el flujo manualmente desde GitHub

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest           # El trabajo de construcción se ejecuta en un runner Ubuntu
    steps:
      - uses: actions/checkout@v4    # Revisa el código del repositorio

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3  # Inicia sesión en GHCR
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Nombre del usuario (GitHub)
          password: ${{ secrets.GITHUB_TOKEN }} # Token de autenticación

      - name: 'Build Inventory Image'
        run: |
          docker build --progress=plain . --tag ghcr.io/${{ github.actor }}/shorten:${{ github.sha }}  # Crea la imagen
          docker push ghcr.io/${{ github.actor }}/shorten:${{ github.sha }}  # Empuja la imagen al GHCR

  deploy:
    permissions:
      contents: none                # No se requiere permisos adicionales para el despliegue
    runs-on: ubuntu-latest           # El trabajo de despliegue también se ejecuta en un runner Ubuntu
    needs: build                     # El despliegue depende del trabajo de construcción
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Desplegar a Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2  # Usa la acción oficial de Azure para el despliegue
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}  # Nombre de tu aplicación en Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Perfil de publicación
          images: ghcr.io/${{ github.actor }}/shorten:${{ github.sha }}  # Imagen de contenedor a desplegar
